# Generated by Django 4.1.7 on 2023-11-19 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_servicelocation_alter_service_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.TextField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.service')),
            ],
            options={
                'db_table': 'service_locations',
            },
        ),
    ]
