# Generated by Django 4.1.7 on 2023-11-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_insert_service_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='content',
        ),
        migrations.RemoveField(
            model_name='location',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='content',
        ),
        migrations.RemoveField(
            model_name='service',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='servicelocation',
            name='title',
        ),
    ]
