# Generated by Django 4.1.7 on 2023-11-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_marketing_button_clicked_marketing_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
