# Generated by Django 4.1.7 on 2023-11-24 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_marketing_button_clicked'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=36, unique=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.lead')),
            ],
            options={
                'db_table': 'lead_image',
            },
        ),
    ]
