# Generated by Django 4.1.7 on 2023-11-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_leadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadimage',
            name='src',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
