# Generated by Django 4.1.7 on 2023-12-25 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_leadimage_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leadimage',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.lead'),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='ad_campaign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='ad_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='landing_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='referrer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
