# Generated by Django 4.1.7 on 2024-07-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_marketing_gclid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='os',
        ),
    ]
