# Generated by Django 4.1.7 on 2024-07-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_marketing_device_type_remove_marketing_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_pets',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='square_feet',
            field=models.FloatField(null=True),
        ),
    ]
