# Generated by Django 4.1.7 on 2024-07-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_lead_bathrooms_lead_bedrooms_lead_has_pets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_house',
            field=models.BooleanField(null=True),
        ),
    ]
