# Generated by Django 4.1.7 on 2024-07-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_lead_is_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='bedrooms',
            new_name='pets',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='has_pets',
        ),
        migrations.AddField(
            model_name='lead',
            name='total_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
